name: 'xero'
version: '0.1.0'
config-version: 2
require-dbt-version: [">=0.19.0", "<0.20.0"]

vars:
  xero:
    account: "{{ ref('stg_xero__account') }}" 
    contact: "{{ ref('stg_xero__contact') }}" 
    invoice_line_item: "{{ ref('stg_xero__invoice_line_item') }}" 
    invoice: "{{ ref('stg_xero__invoice') }}" 
    journal_line: "{{ ref('stg_xero__journal_line') }}" 
    journal: "{{ ref('stg_xero__journal') }}" 
    organization: "{{ ref('stg_xero__organization') }}" 

models:
  xero:
    +materialized: table
    +schema: xero