name: 'xero_integration_tests'
version: '0.5.0'
profile: 'integration_tests'
config-version: 2
vars:
  xero_source:
    xero_account_identifier: "xero_account_data"
    xero_contact_identifier: "xero_contact_data"
    xero_invoice_line_item_identifier: "xero_invoice_line_item_data"
    xero_invoice_identifier: "xero_invoice_data"
    xero_journal_line_identifier: "xero_journal_line_data"
    xero_journal_identifier: "xero_journal_data"
    xero_organization_identifier: "xero_organization_data"
    xero_bank_transaction_identifier: "xero_bank_transaction_data"
    xero_credit_note_identifier: "xero_credit_note_data"
  xero:
    account: "{{ ref('stg_xero__account') }}"
    contact: "{{ ref('stg_xero__contact') }}"
    invoice_line_item: "{{ ref('stg_xero__invoice_line_item') }}"
    invoice: "{{ ref('stg_xero__invoice') }}"
    journal_line: "{{ ref('stg_xero__journal_line') }}"
    journal: "{{ ref('stg_xero__journal') }}"
    organization: "{{ ref('stg_xero__organization') }}"
